// Runs the chained dating model (src/dating/chain.js) with the calibrated parameters and sweeps
// the assumptions that matter. Writes docs/dating/results.md. Run after sensitivity.mjs (it reads
// src/data/dating/calibration.json): node scripts/dating/chain.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import * as D from '../../src/dating/model.js';
import * as C from '../../src/dating/chain.js';
import { normCdf } from '../../src/model.js';

const read = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url)));
const data = read('../../src/data/dating/digitized.json');
const pools = read('../../src/data/dating/pools.json');
const cal = read('../../src/data/dating/calibration.json');

const pct = (v, d = 0) => (v * 100).toFixed(d) + '%';
const ord = (v) => { const n = Math.round(v * 100), s = n % 100 >= 11 && n % 100 <= 13 ? 'th' : ({ 1: 'st', 2: 'nd', 3: 'rd' }[n % 10] ?? 'th'); return n + s; };
const table = (head, rows) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
const md = [];
const say = (...s) => md.push(...s, '');

// ---------- calibrated inputs ----------
const meanOf = (h) => D.histMean(D.histPoints(h));
const W = D.activityWeighted(D.histPoints(data.luap_like_rate_women), meanOf(data.luap_received_ratio_men)).pts;
const Mn = D.activityWeighted(D.histPoints(data.luap_like_rate_men), meanOf(data.luap_received_ratio_women)).pts;
const rhoW = cal.consensus.womenOnMen, rhoM = cal.consensus.menOnWomen;
const demandM = C.demandCurve(D.attentionMarket({ rho: rhoW, openness: W, M: 1000 }));
const demandW = C.demandCurve(D.attentionMarket({ rho: rhoM, openness: Mn, M: 1000 }));
const likeM = C.likeRateCurve(demandM, 0.33);    // men's like rate by looks (median 33%)
const likeW = C.likeRateCurve(demandW, 0.045);   // women's like rate by looks (median 4.5%)
const { b, kc, x50 } = cal.commitment;
const ok = data.okcupid_age;
const interest = (age) => D.curveAt(ok, 'women', age);
// Census never-married share of men by age, forced non-increasing (it is a cross-section).
const census = {};
let prev = 1;
for (const r of pools.by_age.filter((x) => x.sex === 'men')) { prev = Math.min(prev, r.never_married); census[r.age] = prev; }

// Defaults (assumptions; each is swept below).
const BASE = {
  rhoQz: 0.2,      // looks vs long-term partner quality
  lemon: 0.46,     // Connor: relationships end sooner for people worse than they look
  theta: 0,        // how much real quality speeds first marriage (cohort)
  bar: 0.9,        // success = serious and top 10% on partner quality
  n: 10,           // people you can properly evaluate over the whole search
  years: 1,
  womenCasual: 0.15,
};
// Per year of searching. a: weight of looks in the read, c: weight of real quality.
const CHANNELS = {
  app: { label: 'App', a: rhoW, c: 0.1, views: 15000 },                 // ~40 profiles a day
  friends: { label: 'Friends', a: 0.3, c: 0.5, views: 60, like: 0.2 },  // introductions; friends vouch
  work: { label: 'Work', a: 0.25, c: 0.65, views: 25, like: 0.2 },      // people you see for months
};

const menPop = (o = {}) => C.population({ rhoQz: o.rhoQz ?? BASE.rhoQz, casual: o.casual ?? b });
const menSingle = (o = {}) => C.singlePool(menPop(o), { demand: demandM, x50: o.x50 ?? x50, kc: o.kc ?? kc, lemon: o.lemon ?? BASE.lemon });

// A woman (looks z-score y) searching men.
function womanSearch(pool, ch, o = {}) {
  const C0 = CHANNELS[ch], years = o.years ?? BASE.years;
  const y = o.y ?? 0;
  const yEff = o.ageFactor != null && o.ageFactor < 1 ? C.shiftForFactor(pool, likeM, rhoM, y, o.ageFactor) : y;
  return C.search(pool, {
    a: o.a ?? C0.a, c: o.c ?? C0.c, rhoQz: o.rhoQz ?? BASE.rhoQz,
    exposure: ch === 'app' ? cal.exposure.men : 0,
    likeRate: C0.like ?? likeW(normCdf(y)),
    back: C.backRule(likeM, rhoM, yEff),
    views: (o.views ?? C0.views) * years, n: o.n ?? BASE.n, bar: o.bar ?? BASE.bar,
  });
}

say('# Dating model: chained results', '',
  'Generated by `node scripts/dating/chain.mjs` from the calibrated parameters in `src/data/dating/calibration.json`.',
  'One grid of people (looks z, partner quality Q, serious or casual) runs through demand → who is single →',
  'search → outcomes. Everyone\'s bar rises with their options (men\'s median like rate 33%, women\'s 4.5%).',
  'Defaults: looks-quality correlation ρ_Qz = 0.2, lemon effect 0.46, success = a serious partner in the top 10%',
  'on quality, 10 people properly evaluated over the whole search, one year of searching. Every default is swept below.');

// ---------- A. The pool ----------
const single = menSingle();
const res = { app: womanSearch(single.cells, 'app'), friends: womanSearch(single.cells, 'friends'), work: womanSearch(single.cells, 'work') };
const rowsA = [];
const addA = (label, d) => rowsA.push([label, pct(d.serious), ord(d.zPct), ord(d.qPct), pct(d.good, 1)]);
addA('All men', C.describe(menPop().cells));
addA(`Single men (${pct(single.singleShare)} of men)`, C.describe(single.cells));
addA('Single men, no lemon effect', C.describe(menSingle({ lemon: 0 }).cells));
for (const ch of ['app', 'friends', 'work']) addA(`Men she evaluates (${CHANNELS[ch].label.toLowerCase()})`, res[ch]);
say('## A. Who is left, and who she ends up dating', '',
  'Median woman, one year of searching. Looks and quality percentiles are against all men.');
say(table(['Group', 'Serious', 'Looks', 'Quality', 'Serious and top-10% quality'], rowsA));
say(`On the app she matches ${res.app.matches.toFixed(0)} men and has time for ${BASE.n}, so she keeps the best-looking`,
  `${pct(res.app.keepShare, 1)} of her matches. Through friends she gets ${res.friends.matches.toFixed(1)} mutual prospects a year; at work ${res.work.matches.toFixed(1)}.`);

// ---------- B. Channels ----------
const chRows = [];
for (const rhoQz of [0, 0.2, 0.4]) for (const lemon of [0, 0.46]) for (const years of [1, 5]) {
  const pool = menSingle({ rhoQz, lemon }).cells;
  const r = ['app', 'friends', 'work'].map((ch) => womanSearch(pool, ch, { rhoQz, years }));
  chRows.push([rhoQz, lemon, years, ...r.map((x) => `${pct(x.odds)} (${x.evaluated.toFixed(1)} × ${pct(x.good, 1)}, ${pct(x.serious)} serious)`)]);
}
say('## B. Channels', '',
  'Chance she properly evaluates at least one serious, top-10% man: odds (people evaluated × hit rate each, share',
  'serious). Apps win on volume and lose on what you can read. Searching longer on an app does not help much: with',
  'more matches she just keeps better-looking men, who are less often serious.');
say(table(['Looks-quality ρ', 'Lemon', 'Years', 'App', 'Friends', 'Work'], chRows));
const readRows = [0, 0.1, 0.25, 0.4].map((c) => { const x = womanSearch(single.cells, 'app', { c }); return [c, pct(x.serious), ord(x.zPct), ord(x.qPct), pct(x.odds)]; });
say('How much real quality an app profile shows (c = weight of quality in her read):');
say(table(['c', 'Serious', 'Looks', 'Quality', 'Odds'], readRows));
const lookRows = [rhoW, 0.3, 0.1].map((a) => { const x = womanSearch(single.cells, 'app', { a }); return [a.toFixed(2), pct(x.serious), ord(x.zPct), ord(x.qPct), pct(x.odds)]; });
say('How much she swipes on looks (a; the fitted consensus is the default):');
say(table(['a', 'Serious', 'Looks', 'Quality', 'Odds'], lookRows));

// ---------- C. Her age ----------
const coh = (theta) => C.cohort(menPop(), { demand: demandM, kc, theta, census });
const cohorts = { 0: coh(0), 0.3: coh(0.3) };
const ageRows = [];
for (const age of [22, 25, 28, 30, 33, 35, 38, 40]) {
  const af = interest(age);
  const pool = cohorts[0][Math.min(60, age + 2)].cells;   // never-married men about two years older
  const x = womanSearch(pool, 'app', { ageFactor: af });
  const xq = womanSearch(cohorts[0.3][Math.min(60, age + 2)].cells, 'app', { ageFactor: af });
  const hot = womanSearch(pool, 'app', { ageFactor: af, y: 1 });
  ageRows.push([age, pct(af), x.matches.toFixed(0), pct(x.pool.serious), pct(x.serious), ord(x.zPct), pct(x.odds), pct(hot.odds), pct(xq.odds), pct(D.fecundityUsed(data.geruso, age, 20))]);
}
say('## C. Her age', '',
  'Her pool is never-married men two years older (the cohort model in E: who is still single at that age).',
  'Interest in her falls with age (OkCupid curve); it is applied as a shift in her looks, so the men with the most',
  'options stop liking her back first. One year on an app, 10 evaluated. A top-16% woman (one SD up) and the',
  'cohort with quality helping marriage (θ = 0.3) are shown alongside. Fecundity used is from age 20.');
say(table(['Her age', 'Interest vs peak', 'Matches', 'Pool serious', 'Serious (dated)', 'Looks of men dated', 'Odds (median)', 'Odds (top 16%)', 'Odds (θ = 0.3)', 'Fecundity used'], ageRows));

// ---------- D. His side ----------
const womenPop = C.population({ rhoQz: BASE.rhoQz, casual: BASE.womenCasual });
const womenSingle = C.singlePool(womenPop, { demand: demandW, x50, kc: 1, lemon: BASE.lemon });
const manRows = [0.5, 0.75, 0.9, 0.99, 0.999].map((u) => {
  const y = D.zTop(1 - u);
  const back = C.backRule(likeW, rhoW, y);
  const run = (bar, n = BASE.n) => C.search(womenSingle.cells, { a: rhoM, c: 0.1, rhoQz: BASE.rhoQz, exposure: cal.exposure.women, likeRate: likeM(u), back, views: 15000, n, bar });
  const s = run(0.9), s99 = run(0.99), s999 = run(0.999, 20), s9999 = run(0.9999, 20);
  const avgBack = womenSingle.cells.reduce((acc, c) => acc + c.w * back(c), 0);
  return [ord(u), pct(likeM(u)), pct(avgBack, 1), s.matches.toFixed(0), ord(s.zPct), ord(s.qPct), pct(s.odds), pct(s99.odds, 1), pct(s999.odds, 2), pct(s9999.odds, 2)];
});
say('## D. His side', '',
  'Men by looks percentile, one year on an app (15,000 profiles). His like rate falls with his options; each woman',
  'likes him back at her own rate, which also falls with hers. Women\'s intent is flat in looks, so no commitment filter',
  'on them, only the lemon effect. Success = serious and top 10% / 1% / 0.1% / 0.01% on quality.');
say(table(['His looks', 'He likes', 'Women like him', 'Matches', 'Looks of women he dates', 'Their quality', 'Top 10%', 'Top 1%', 'Top 0.1% (n = 20)', 'Top 0.01% (n = 20)'], manRows));
// The author's top-1% man looking for a 1-in-1k or 1-in-10k wife, by how well he can read quality.
const topMan = (c, bar) => C.search(womenSingle.cells, { a: Math.min(rhoM, Math.sqrt(1 - c * c) * 0.9), c, rhoQz: BASE.rhoQz, exposure: cal.exposure.women,
  likeRate: likeM(0.999), back: C.backRule(likeW, rhoW, D.zTop(0.001)), views: 15000 * 5, n: 20, bar });
const cRows = [0.1, 0.3, 0.5, 0.7, 0.9].map((c) => [c, pct(topMan(c, 0.999).odds, 1), pct(topMan(c, 0.9999).odds, 1), pct(topMan(c, 0.999996).odds, 2)]);
say('The 99.9th-percentile man over five years, 20 women properly evaluated, by how much real quality shows before',
  'he invests (c; his weight on looks shrinks as c grows). The author\'s table assumes a perfect read of a top-1% pool:',
  '88% / 18% / 0.8% for 1 in 1k / 10k / 250k.');
say(table(['c', '1 in 1k', '1 in 10k', '1 in 250k'], cRows));

// ---------- E. Never-married men by age ----------
const cohRows = [];
for (const theta of [0, 0.3]) for (const age of [25, 30, 35, 40, 45, 50]) {
  const d = C.describe(cohorts[theta][age].cells);
  cohRows.push([theta, age, pct(cohorts[theta][age].never), pct(1 - d.serious), ord(d.zPct), ord(d.qPct), pct(d.good, 1)]);
}
const kcRows = [0, 0.1, 0.2, 0.5].map((k) => {
  const c = C.cohort(menPop(), { demand: demandM, kc: k, census });
  const d = C.describe(c[40].cells);
  return [k, pct(1 - d.serious), ord(d.zPct), ord(d.qPct)];
});
say('## E. Never-married men by age', '',
  'Frailty model: the population first-marriage rate is fitted to the census never-married curve at every age, so',
  'the output is only who is left. A man\'s propensity = intent (casual men at k_c) × demand from his looks × e^(θQ).');
say(table(['θ', 'Age', 'Never married (census)', 'Casual', 'Looks', 'Quality', 'Serious and top-10% quality'], cohRows));
say('Never-married men at 40 by how slowly casual men pair off (k_c):');
say(table(['k_c', 'Casual', 'Looks', 'Quality'], kcRows));
const nm = pools.never_married_40_49;
say(`Census check on who is left (men 40-49, never vs ever married): median earnings $${Math.round(nm.men_never.median_earnings / 1000)}k vs`,
  `$${Math.round(nm.men_ever.median_earnings / 1000)}k, BA+ ${pct(nm.men_never.ba_plus)} vs ${pct(nm.men_ever.ba_plus)}. The model has no earnings; it predicts the same direction on looks and intent.`);

// ---------- F. What moves her odds ----------
const base = res.app.odds;
const at = (fn) => fn().odds;
const tornado = [
  ['Looks-quality ρ 0 → 0.4', at(() => womanSearch(menSingle({ rhoQz: 0 }).cells, 'app', { rhoQz: 0 })), at(() => womanSearch(menSingle({ rhoQz: 0.4 }).cells, 'app', { rhoQz: 0.4 }))],
  ['Lemon effect 0 → 1', at(() => womanSearch(menSingle({ lemon: 0 }).cells, 'app')), at(() => womanSearch(menSingle({ lemon: 1 }).cells, 'app'))],
  ['Casual pair-off rate k_c 0 → 0.2', at(() => womanSearch(menSingle({ kc: 0 }).cells, 'app')), at(() => womanSearch(menSingle({ kc: 0.2 }).cells, 'app'))],
  ['Quality shown in profile c 0 → 0.4', at(() => womanSearch(single.cells, 'app', { c: 0 })), at(() => womanSearch(single.cells, 'app', { c: 0.4 }))],
  ['Weight on looks a 0.48 → 0.1', base, at(() => womanSearch(single.cells, 'app', { a: 0.1 }))],
  ['People evaluated n 4 → 20', at(() => womanSearch(single.cells, 'app', { n: 4 })), at(() => womanSearch(single.cells, 'app', { n: 20 }))],
  ['Years searching 1 → 5', base, at(() => womanSearch(single.cells, 'app', { years: 5 }))],
  ['Her age 25 → 35 (cohort pool)', ageRows[1][6], ageRows[5][6]],
].map(([k, lo, hi]) => {
  const f = (v) => (typeof v === 'string' ? parseFloat(v) / 100 : v);
  return [k, pct(f(lo)), pct(f(hi)), `${((f(hi) - f(lo)) * 100).toFixed(0)} pts`];
});
say('## F. What moves her odds most', '', `Median woman, one year on an app, default odds ${pct(base)}. Each row moves one assumption.`);
say(table(['Assumption', 'Low', 'High', 'Swing'], tornado));

writeFileSync(new URL('../../docs/dating/results.md', import.meta.url), md.join('\n'));
console.log('wrote docs/dating/results.md');
