// Runs the calibrated dating model (src/dating/scenario.js) and sweeps the assumptions that matter.
// Writes docs/dating/results.md. Run after fit.mjs (it reads src/data/dating/fitted.json):
//   node scripts/dating/chain.mjs
// The mate-value searches run on the coarse grid (the page's grid).
import { readFileSync, writeFileSync } from 'node:fs';
import * as D from '../../src/dating/model.js';
import { createScenario } from '../../src/dating/scenario.js';

const read = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url)));
const inputs = {
  digitized: read('../../src/data/dating/digitized.json'), pools: read('../../src/data/dating/pools.json'),
  calibration: read('../../src/data/dating/calibration.json'), nsfg: read('../../src/data/dating/nsfg.json'),
  status: read('../../src/data/dating/status.json'),
};
const fitted = read('../../src/data/dating/fitted.json'), assort = read('../../src/data/dating/assort.json'), glp1 = read('../../src/data/dating/glp1.json');
const S = createScenario(inputs, { grid: 'coarse', fitted });
const { herYears, hisYears, censusW } = S;

const pct = (v, d = 0) => (v * 100).toFixed(d) + '%';
const ord = (v) => { const n = Math.round(v * 100), s = n % 100 >= 11 && n % 100 <= 13 ? 'th' : ({ 1: 'st', 2: 'nd', 3: 'rd' }[n % 10] ?? 'th'); return n + s; };
const table = (head, rows) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
const md = [];
const say = (...s) => md.push(...s, '');
const t0 = Date.now();
const log = (m) => console.log(`${((Date.now() - t0) / 1000).toFixed(0)}s ${m}`);
const oddsRow = (o) => [pct(o.any), pct(o.rare), pct(o.top10, 1), pct(o.top5, 1), pct(o.top1, 2)];

say('# Dating model: results', '',
  'Generated by `node scripts/dating/chain.mjs` from the fitted constants in `src/data/dating/fitted.json`.',
  'Two layers: the attention market on the apps (looks: who gets likes, matches, first dates; Acts II-III) and mate',
  'value (who commits to whom). A man\'s mate value is the author\'s dating power mix (status 0.5, social skills 0.2, looks',
  '0.2, height 0.1); a woman\'s is her appeal for her age, shifted down with age (OkCupid). After a first date both must',
  'want to keep seeing each other; after months, each commits if the other is near or above their own level (less a',
  'tolerance, plus a premium for their options), and the relationship then works out with a fitted chance.',
  'Mate-value searches run on the coarse grid the page uses.');

// ---------- A. The fit ----------
say('## A. What the free parameters are fitted to', '',
  table(['Parameter', 'Value', 'Fitted to', 'Model', 'Data'], [
    ['theta (higher-value men marry faster)', fitted.theta, 'ever married at 40-49 by earnings quintile (ACS)', fitted.checks.marriageByEarnings.model.map((x) => pct(x)).join(' '), fitted.checks.marriageByEarnings.acs.map((x) => pct(x)).join(' ')],
    ['tolerance (how far below their level people commit)', fitted.tolerance, 'couples\' latent status correlation (PSID)', fitted.checks.couplesCorrelation.model.toFixed(3), fitted.checks.couplesCorrelation.target.toFixed(3)],
    ['commitScale (a mutual commitment works out)', fitted.commitScale, 'never-married women 25 married by 30 (census)', '(fitted exactly)', pct(fitted.checks.census25to30, 1)],
  ]),
  'The couples target comes from `scripts/dating/assort.py`: a two-factor model on PSID couple-years 2000+ (the husband\'s',
  'own earnings and education against his wife\'s father\'s peak income, wealth and education and her own education, with',
  `education allowed to match directly) gives a latent status correlation of ${assort.cfa.rho.toFixed(2)}. The raw composite correlation`,
  `is ${assort.rho_composite.toFixed(2)} (measurement noise pulls it down). The author's cascade (near-match on wealth or income, else the wife`,
  `has at least his education) reproduces exactly: ${pct(assort.observed.matched, 1)} matched, ${pct(assort.observed.cascade.mismatch, 1)} full mismatch (n = ${assort.observed.n.toLocaleString('en-US')}).`,
  `But random pairing would already score ${pct(assort.fits[0].matched, 1)} on the same lenient criteria, so the cascade cannot pin down how tightly`,
  `couples sort; simulated at the latent 0.76 it gives ${pct(assort.fits.find((f) => f.rho === 0.76).matched, 1)}.`);
log('A');

// ---------- B. Commitment ----------
const his = S.hisCommit();
const manAt = (p) => ({ Q: D.zTop(1 - p), u: 0.5, serious: true, M: 30 });
say('## B. Will he commit?', '',
  'A serious man of 30 who has dated a woman of 28 for months: would he commit (his decision alone), by his mate-value',
  `percentile and hers. Whether the relationship then works out is a further ${pct(S.BASE.commitScale)} (commitScale), for both.`,
  table(['His percentile', 'Her 10th', 'Her 50th', 'Her 75th', 'Her 90th', 'Her 99th'],
    [0.1, 0.25, 0.5, 0.75, 0.9, 0.95, 0.99].map((p) => [ord(p), ...[0.1, 0.5, 0.75, 0.9, 0.99].map((v) => pct(his(manAt(p), D.zTop(1 - v) + S.womenShift(28)) / S.BASE.commitScale, 1))])));

// ---------- C. Her odds ----------
say('## C. Her odds over five years from 25, by her appeal for her age', '',
  'Any committed man; one at least as rare as she is; one in the top 10 / 5 / 1% of men by mate value.',
  table(['Her appeal', 'Any', 'As rare', 'Top 10%', 'Top 5%', 'Top 1%', 'Matches, year 1'],
    [0.1, 0.25, 0.5, 0.75, 0.9, 0.99].map((v) => { const r = herYears({ v }); return [ord(v), ...oddsRow(r.odds), Math.round(r.first.matches)]; })));
log('C');

// ---------- D. Age ----------
say('## D. By the age she starts (a median woman), against the census', '',
  'Census: the share of never-married women at that age who marry within five years.',
  table(['Start', 'Any', 'As rare', 'Top 10%', 'Census'],
    [22, 24, 26, 28, 30, 32, 34, 36, 38].map((start) => { const r = herYears({ start }); const c = censusW[start + 5] != null ? 1 - censusW[start + 5] / censusW[start] : null; return [start, pct(r.odds.any), pct(r.odds.rare), pct(r.odds.top10, 1), c == null ? '—' : pct(c)]; })),
  'Age gaps (open to men up to `gap` years older), a median woman:',
  table(['Start', 'Gap', 'Any', 'As rare', 'Top 10%', 'Top 5%'],
    [23, 27, 31].flatMap((start) => [2, 5, 10, 15].map((gap) => { const r = herYears({ start, gap }); return [start, gap, pct(r.odds.any), pct(r.odds.rare), pct(r.odds.top10, 1), pct(r.odds.top5, 1)]; }))),
  'A 90th-percentile woman:',
  table(['Start', 'Gap', 'Any', 'Top 10%', 'Top 5%', 'Top 1%'],
    [23, 27, 31].flatMap((start) => [2, 10, 15].map((gap) => { const r = herYears({ start, gap, v: 0.9 }); return [start, gap, pct(r.odds.any), pct(r.odds.top10, 1), pct(r.odds.top5, 1), pct(r.odds.top1, 2)]; }))));
log('D');

// ---------- E. His odds ----------
say('## E. His odds over five years from 30 (women 22-30), by his mate value', '',
  table(['His percentile', 'Looks pctile (expected)', 'First dates / yr', 'Any', '50th+', '75th+', '90th+', '95th+', 'As rare'],
    [0.1, 0.25, 0.5, 0.75, 0.9, 0.99].map((mv) => { const r = hisYears({ age: 30, mv, lo: 22, hi: 30 }); return [ord(mv), ord(r.uLooks), r.first.dates.toFixed(2), pct(r.odds.any), pct(r.odds.p50), pct(r.odds.p75, 1), pct(r.odds.p90, 1), pct(r.odds.p95, 1), pct(r.odds.rare)]; })),
  'One thing at a time, from a median man of 30:',
  table(['Change', 'Value pctile', 'Any', '75th+', '90th+'],
    [['Baseline', {}], ['Status 75th', { status: 0.75 }], ['Status 90th', { status: 0.9 }], ['Looks 75th', { uLooks: 0.75 }], ['Social 75th', { social: 0.75 }], ['Height 90th', { height: 0.9 }], ['All three 75th', { status: 0.75, uLooks: 0.75, social: 0.75 }], ['Friends, not apps', { ch: 'friends' }]]
      .map(([l, o]) => { const r = hisYears({ age: 30, lo: 22, hi: 30, uLooks: 0.5, ...o }); return [l, ord(r.mvPct), pct(r.odds.any), pct(r.odds.p75, 1), pct(r.odds.p90, 1)]; })));
log('E');

// ---------- F. Women's levers ----------
const gb = (lo) => glp1.bands.find((b) => Math.abs(b.band[0] - lo) < 1e-6);
const vG = S.appealFromWhr((gb(0.25).pct_glp1_glutes + gb(0.5).pct_glp1_glutes) / 2);
say('## F. What moves a median woman\'s odds (from 27, five years)', '',
  table(['Lever', 'Any', 'As rare', 'Top 10%', 'Top 5%', 'Top 1%'],
    [['Baseline', {}], ['Start at 23', { start: 23 }], ['Gap 10', { gap: 10 }], ['Gap 15', { gap: 15 }], [`GLP-1 + glutes (appeal ${ord(vG)})`, { v: vG }], ['Three men a year', { n: 3 }], ['Friends, not apps', { ch: 'friends' }], ['No app options premium (kappa 0)', { kappa: 0 }]]
      .map(([l, o]) => [l, ...oddsRow(herYears({ start: 27, v: 0.5, gap: 2, ...o }).odds)])),
  'GLP-1s and glute training, by where she starts on WHR (NHANES women 20-29, simulated responses; `glp1.json`):',
  table(['Start band', 'WHR', 'Reach ≤ 0.74 now / GLP-1 / + glutes', 'WHR pctile after (GLP-1 / + glutes)'],
    glp1.bands.map((b) => [`top ${pct(b.band[0])}-${pct(b.band[1])}`, b.whr_median.toFixed(3), `${pct(b.qualify_now)} / ${pct(b.qualify_glp1)} / ${pct(b.qualify_glp1_glutes)}`, `${ord(b.pct_glp1)} / ${ord(b.pct_glp1_glutes)}`])));
log('F');

// ---------- G. Marriage by cohort ----------
const co = inputs.digitized.cohorts, at = (c, a) => co[c].find(([x]) => x === a)?.[1];
say('## G. Where the marriage decline happened (census cohorts, digitized)', '',
  table(['Born', 'Married by 25', 'By 30', 'Single at 25 who marry by 30'],
    ['1940', '1950', '1960', '1970', '1980', '1990'].map((c) => [c + 's', pct(at(c, 25)), pct(at(c, 30)), pct(1 - (1 - at(c, 30)) / (1 - at(c, 25)))])),
  'The 1980s cohort turned 30 around 2010, before Tinder; the 1990s cohort dated from 25 to 30 on the apps. The 25-to-30',
  'transition is the same for both, so the app-era fall is all in marriage before 25, and most of the fall since the',
  '1950s predates the apps.');

// ---------- H. Sensitivity ----------
const base = { start: 27, v: 0.5, gap: 2 }, top = { start: 25, v: 0.9, gap: 2 };
const sweep = [
  ['Commitment noise sigma (0.5)', 'sigma', 0.35, 0.65],
  ['Options premium kappa (0.25)', 'kappa', 0, 0.5],
  [`Tolerance (${fitted.tolerance})`, 'tolerance', fitted.tolerance - 0.15, fitted.tolerance + 0.15],
  [`Commit scale (${fitted.commitScale})`, 'commitScale', fitted.commitScale * 0.75, fitted.commitScale * 1.25],
  ['Profile read of status c (0.2)', 'c', 0.1, 0.3],
];
const rows = [];
for (const [label, k, lo, hi] of sweep) {
  const r0 = herYears({ ...base, [k]: lo }).odds, r1 = herYears({ ...base, [k]: hi }).odds, q0 = herYears({ ...top, [k]: lo }).odds, q1 = herYears({ ...top, [k]: hi }).odds;
  rows.push([label, `${lo.toFixed(2)} → ${hi.toFixed(2)}`, `${pct(r0.any)} → ${pct(r1.any)}`, `${pct(r0.rare)} → ${pct(r1.rare)}`, `${pct(q0.top10)} → ${pct(q1.top10)}`]);
}
const b0 = herYears(base).odds, bt = herYears(top).odds;
say('## H. Sensitivity (not refitted: each assumption moved alone)', '',
  `Baseline: a median woman from 27 (any ${pct(b0.any)}, as rare ${pct(b0.rare)}); a 90th-percentile woman from 25 (top 10% ${pct(bt.top10)}).`,
  table(['Assumption (default)', 'Range', 'Median woman: any', 'Median woman: as rare', '90th pctile: top 10%'], rows),
  'Fixed assumptions: the dating-power weights; how much of women\'s age preference lowers an older man\'s bar (0.5);',
  'a first-date read twice as noisy as the committed one; casual men keep dating a woman who likes them 80% of the time;',
  'half of casual men are recognizable from the profile; two men properly dated a year.');
log('H');

writeFileSync(new URL('../../docs/dating/results.md', import.meta.url), md.join('\n'));
log('wrote docs/dating/results.md');
