// Calibrates the dating models to the digitized data and sweeps the parameters readers will control.
// Writes src/data/dating/calibration.json (fitted parameters the page uses) and
// docs/dating/sensitivity.md (tables for review). Run: node scripts/dating/sensitivity.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import * as D from '../../src/dating/model.js';
import { steadyState, JOB_TYPES } from '../../src/model.js';

const read = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url)));
const data = read('../../src/data/dating/digitized.json');
const pools = read('../../src/data/dating/pools.json');
const gss = read('../../src/data/dating/gss.json');

const pct = (v, d = 0) => (v * 100).toFixed(d) + '%';
const oneIn = (p) => { const n = 1 / p; return n >= 1e6 ? `1 in ${(n / 1e6).toFixed(1)}M` : n >= 1e4 ? `1 in ${Math.round(n / 1e3)}k` : `1 in ${Math.round(n).toLocaleString('en-US')}`; };
const table = (head, rows) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
const md = [];
const say = (...s) => md.push(...s, '');

// ---------- 1. Attention market ----------
const meanOf = (h) => D.histMean(D.histPoints(h));
const W = D.activityWeighted(D.histPoints(data.luap_like_rate_women), meanOf(data.luap_received_ratio_men));
const Mn = D.activityWeighted(D.histPoints(data.luap_like_rate_men), meanOf(data.luap_received_ratio_women));
const VIEWS = 100;
const fitW = D.fitConsensus(data.luap_received_ratio_men, W.pts, { views: VIEWS });
const fitM = D.fitConsensus(data.luap_received_ratio_women, Mn.pts, { views: VIEWS });
const rhoW = +fitW.rho.toFixed(2), rhoM = +fitM.rho.toFixed(2);
const HINGE = { men: { top1: 0.16, top5: 0.41, top10: 0.58, bottom50: 0.04 }, women: { top1: 0.11, top5: 0.31, top10: 0.46, bottom50: 0.08 } };
const kappaW = D.fitExposure(rhoW, W.pts, HINGE.men.top5);
const kappaM = D.fitExposure(rhoM, Mn.pts, HINGE.women.top5);
const menEq = D.attentionMarket({ rho: rhoW, openness: W.pts, views: VIEWS });
const menHi = D.attentionMarket({ rho: rhoW, openness: W.pts, kappa: kappaW });
const womenEq = D.attentionMarket({ rho: rhoM, openness: Mn.pts, views: VIEWS });
const womenHi = D.attentionMarket({ rho: rhoM, openness: Mn.pts, kappa: kappaM });

say('# Dating models: calibration and sensitivities', '',
  'Generated by `node scripts/dating/sensitivity.mjs`. Inputs: `src/data/dating/*.json` (digitized charts, the',
  'Dating Calculator parquet, GSS). Every number below is recomputed on each run.');

say('## 1. Attention market', '',
  'Viewers agree on attractiveness with correlation ρ and each likes a fixed share of what she is shown. ρ is',
  `fitted to the app founder's received-ratio histograms (${VIEWS} views per profile; like rates weighted by`,
  `activity with exponent ${W.a.toFixed(2)} for women and ${Mn.a.toFixed(2)} for men so their means match the received means).`);
say(table(['Side', 'Fitted consensus ρ', 'KS distance', 'Median received (model / data)'], [
  ['Women rating men', rhoW, fitW.d.toFixed(3), `${pct(menEq.ratioP50, 1)} / 4.5%`],
  ['Men rating women', rhoM, fitM.d.toFixed(3), `${pct(womenEq.ratioP50, 1)} / 38.5%`],
]));
say('Men agree more about women than women do about men. The concentration on men comes from how few',
  'profiles women like, not from stronger agreement (see the counterfactuals below).');

const shareRow = (label, m, ref) => [label, pct(m.top1), pct(m.top5), pct(m.top10), pct(m.top20), pct(m.bottom50, 1), m.gini.toFixed(2), ref ?? ''];
say('### Share of all likes', '',
  `Equal exposure is the like-ratio view (every profile shown equally). The Hinge rows add an exposure tilt κ`,
  `(views ∝ e^{κz}), fitted to Hinge's top-5% share alone: κ = ${kappaW.toFixed(2)} for men (a top-5% man is shown`,
  `${Math.exp(kappaW * 1.96).toFixed(1)}× as often as the median man), ${kappaM.toFixed(2)} for women. The other Hinge columns are out of sample.`);
say(table(['Who', 'Top 1%', 'Top 5%', 'Top 10%', 'Top 20%', 'Bottom 50%', 'Gini', 'Hinge (1/5/10/bottom 50)'], [
  shareRow('Men, equal exposure', menEq),
  shareRow('Men, Hinge exposure', menHi, '16 / 41 / 58 / 4'),
  shareRow('Women, equal exposure', womenEq),
  shareRow('Women, Hinge exposure', womenHi, '11 / 31 / 46 / 8'),
]));
const g = gss.men.partner_concentration_25_45, gw = gss.women.partner_concentration_25_45;
say(`Offline cross-check (GSS ${gss.source.match(/years (\d+)/)[1]}+, lifetime partners since 18, ages 25-45): the top 5% of men account for`,
  `${pct(g.top_5)} of partners reported by men and the top 10% for ${pct(g.top_10)} (women: ${pct(gw.top_5)} and ${pct(gw.top_10)}).`);

// Counterfactuals: women's like rate and consensus.
const scaled = (pts, f) => pts.map((p) => ({ x: Math.min(0.99, p.x * f), w: p.w }));
const cfRows = [];
for (const f of [0.5, 1, 2, 4]) {
  const row = [`× ${f} (mean ${pct(D.histMean(scaled(W.pts, f)), 1)})`];
  for (const rho of [0.2, rhoW, 0.7]) row.push(pct(D.attentionMarket({ rho, openness: scaled(W.pts, f), kappa: kappaW, M: 1500 }).top5));
  cfRows.push(row);
}
const menAsPicky = D.attentionMarket({ rho: rhoM, openness: W.pts, kappa: kappaM, M: 1500 });
say('### Counterfactual: how picky and how much agreement', '',
  "Top-5% share of men's likes (Hinge exposure) as women's like rates are scaled and consensus varies.");
say(table(["Women's like rates", 'ρ = 0.2', `ρ = ${rhoW} (fitted)`, 'ρ = 0.7'], cfRows));
say(`If men liked profiles as rarely as women do, the top 5% of women would get ${pct(menAsPicky.top5)} of men's likes`,
  `(vs ${pct(womenHi.top5)} now).`);

// ---------- 2. Inbox ----------
const inboxRows = [];
for (const ratio of [1, 1.5, 2, 2.7, 3]) {
  const r = D.inboxLoad({ menPerWoman: ratio, swipesPerMan: 100, menLikeRate: D.histMean(Mn.pts), capacity: 5 });
  inboxRows.push([ratio, Math.round(r.incoming), pct(r.answerShare, 1), `top ${pct(r.answerShare, 1)}`]);
}
say('## 2. Inbox load', '',
  `100 swipes per man per day at the activity-weighted male like rate (${pct(D.histMean(Mn.pts))}); a woman has time for 5 conversations a day.`);
say(table(['Men per woman', 'Likes to average woman / day', 'Share she can answer', 'Bar she must set'], inboxRows));

// ---------- 3. Commitment filter ----------
const LUAP_CASUAL = [23, 22, 30, 33, 35, 41, 46, 52];   // % date + sex, least to most attractive (8 groups)
const commitRows = [];
let chosen = null;
for (const kc of [0, 0.1, 0.2]) for (const b of [0.2, 0.23]) {
  const x50 = D.fitCommitment(menEq, { b, kc, topTarget: 0.52, groups: 8 });
  const gps = D.commitmentByPercentile(menEq, { x50, b, kc, groups: 8 });
  const rmse = Math.sqrt(gps.reduce((s, d, i) => s + (d.casualOnApp * 100 - LUAP_CASUAL[i]) ** 2, 0) / 8);
  commitRows.push([kc, pct(b), x50.toFixed(2), gps[7].x.toFixed(1), gps.map((d) => (d.casualOnApp * 100).toFixed(0)).join(' '), rmse.toFixed(1), pct(gps[7].onApp)]);
  if (kc === 0.1 && b === 0.2) chosen = { kc, b, x50, groups: gps };
}
const maxCasual = (b, kc) => b / (b + (1 - b) * kc);
say('## 3. Commitment filter', '',
  'Men differ only in intent: serious men pair off at rate λ, casual men at k_c·λ; relationships end at δ.',
  'λ is proportional to the likes a man gets (equal exposure, the founder\'s app). b is the casual share of all men.',
  `Target: the founder's chart, casual share on the app by attractiveness (8 groups): ${LUAP_CASUAL.join(' ')}.`);
say(table(['k_c', 'b', 'x (median man)', 'x (top group)', 'Model casual share, least to most attractive', 'RMSE (pts)', 'Top group single'], commitRows));
say(`No intent difference by looks is needed: selection alone reproduces the gradient. It requires casual men to pair`,
  `off at under ${pct(0.48 * 0.2 / (0.52 * 0.8), 0)} of the serious rate when b = 20% (at any k_c above b(1−t)/((1−b)t) the top share can never reach`,
  `52%: with k_c = 0.3 the ceiling is ${pct(maxCasual(0.2, 0.3))}). x is how many times faster a serious man pairs off than a relationship ends.`);

// ---------- 4. Reservation value ----------
const resRows = [0.5, 1, 2, 5, 10, 20, 50].map((L) => { const r = D.reservation(L); return [L, r.w.toFixed(2), pct(r.accept, 1), `top ${pct(r.accept, 1)}`]; });
say('## 4. Reservation value (McCall)', '',
  'L = prospects per unit of patience. Relative likes by percentile (Hinge exposure) put the 90th-percentile man at',
  `${menHi.rel.p90.toFixed(1)}× the mean and the median man at ${menHi.rel.p50.toFixed(2)}×: about ${(menHi.rel.p90 / menHi.rel.p50).toFixed(0)}× the prospects.`);
say(table(['L', 'Reservation w (σ)', 'Accepts', 'Only considers']
  , resRows));

// ---------- 5. Age ----------
const ok = data.okcupid_age;
const byAge = (sex, age) => pools.by_age.find((r) => r.sex === sex && r.age === age);
const ageRows = [20, 22, 25, 28, 30, 33, 35, 38, 40, 45].map((a) => {
  const w = byAge('women', a);
  return [a, pct(D.curveAt(ok, 'women', a)), pct(D.curveAt(ok, 'men', a)), pct(D.fecundityUsed(data.geruso, a, 20)), pct(w.whr_le_074, 1), pct(w.whr_ge_085), pct(w.single), pct(byAge('men', a).single)];
});
say('## 5. Age', '',
  'OkCupid interest relative to each sex\'s own peak (women peak at 22, men at 26 on this measure); fecundity used',
  'since age 20 (Geruso et al. 2023, digitized); WHR and single shares from the parquet.');
say(table(['Age', 'Women: interest vs peak', 'Men: interest vs peak', 'Fecundity used (from 20)', 'Women WHR ≤ 0.74', 'Women WHR ≥ 0.85', 'Women single', 'Men single'], ageRows));
const nm = pools.never_married_40_49;
say(`Never-married men at 40-49 (${pct(nm.men_never.share)} of men that age) vs ever-married: median earnings`,
  `$${Math.round(nm.men_never.median_earnings / 1000)}k vs $${Math.round(nm.men_ever.median_earnings / 1000)}k, median net worth $${Math.round(nm.men_never.median_net_worth / 1000)}k vs $${Math.round(nm.men_ever.median_net_worth / 1000)}k,`,
  `BA+ ${pct(nm.men_never.ba_plus)} vs ${pct(nm.men_ever.ba_plus)}, earning $100k+ ${pct(nm.men_never.earn_100k)} vs ${pct(nm.men_ever.earn_100k)}.`);
const mbe = pools.marriage_by_earnings.men_40_49.quintiles;
say(`Ever married by earnings quintile, men 40-49 (age held fixed): ${mbe.map((q) => pct(q.ever_married)).join(' / ')};`,
  `currently married ${mbe.map((q) => pct(q.currently_married)).join(' / ')}.`);

// ---------- 6. Search ----------
const Ns = [1e3, 1e4, 1e5, 2.5e5];
const searchRows = [];
for (const r of [1, 0.7, 0.5, 0.35]) for (const n of [4, 10, 20]) {
  searchRows.push([r === 1 ? 'perfect' : r, n, ...Ns.map((N) => pct(D.findOdds({ n, p: 0.01, N, r }), N >= 1e4 ? 2 : 0)),
    oneIn(1 / D.bestRarity({ n, p: 0.01, r, luck: 0.5 })), oneIn(1 / D.bestRarity({ n, p: 0.01, r, luck: 0.9 }))]);
}
say('## 6. Search: the rarity you can find', '',
  'You go deep only with people in the top 1% of what you can read up front (photos, texts, a first date), and',
  'can properly evaluate n of them. r is how well that up-front read tracks the partner qualities you care about.',
  'Perfect reads reproduce the author\'s table (88% / 18% / 2% / 0.8% at n = 20).');
say(table(['Read r', 'n evaluated', 'P(≥ 1 in 1k)', 'P(≥ 1 in 10k)', 'P(≥ 1 in 100k)', 'P(≥ 1 in 250k)', 'Best found, median luck', 'Best found, 1-in-10 luck'], searchRows));
// Median member of the pool: the rarity N with P(Q above the 1-in-N line | in the pool) = 1/2.
const medianMember = (r) => { let lo = 1, hi = 1e6; for (let i = 0; i < 100; i++) { const m = Math.sqrt(lo * hi); if (D.hitRate(m, 0.01, r) > 0.5) lo = m; else hi = m; } return 1 - 1 / lo; };
say('What a "top 1% on the app" pool is really worth:');
say(table(['Read r', 'Truly in the top 1%', 'Truly in the top 10%', 'Median member\'s true percentile'],
  [1, 0.7, 0.5, 0.35].map((r) => [r === 1 ? 'perfect' : r, pct(D.hitRate(100, 0.01, r)), pct(D.hitRate(10, 0.01, r)), `${(medianMember(r) * 100).toFixed(1)}th`])));
const rar = pools.rarity;
say('### The rarity you are', '',
  `Single men 25-35 (${(rar.men_single_25_35.pool / 1e6).toFixed(1)}M): 6ft+ ${pct(rar.men_single_25_35.six_ft)}, $100k+ ${pct(rar.men_single_25_35.earn_100k)},`,
  `fit ${pct(rar.men_single_25_35.fit, 1)} (the parquet's fit and abs flags are identical); all three ${oneIn(rar.men_single_25_35.six_six_six)}; plus blue eyes and a trust fund`,
  `${oneIn(rar.men_single_25_35.finance_meme)}. Single women 22-27 (${(rar.women_single_22_27.pool / 1e6).toFixed(1)}M): WHR ≤ 0.74 ${pct(rar.women_single_22_27.whr_le_074, 1)},`,
  `plus BA ${oneIn(rar.women_single_22_27.whr_ba)}, plus $100k+ ${oneIn(rar.women_single_22_27.whr_ba_earn_100k)}.`);
const trRows = [];
for (const [k, q] of [[3, 0.1], [4, 0.1], [3, 0.05], [5, 0.2]]) trRows.push([k, `top ${pct(q)}`, ...[0, 0.2, 0.4].map((rho) => oneIn(D.traitRarity({ k, q, rho })))]);
say('How rare "good on everything" is:');
say(table(['Traits', 'Bar on each', 'Independent', 'ρ = 0.2', 'ρ = 0.4'], trRows));

// ---------- 7. Channels ----------
const chRows = D.DATING_CHANNELS.map((ch) => {
  const o = D.channelOdds(ch, { n: 10, N: 1000, years: 1 });
  const o5 = D.channelOdds(ch, { n: 10, N: 1000, years: 5 });
  return [ch.label, pct(ch.met2017), ch.met, ch.r, pct(o.p, o.p < 0.1 ? 1 : 0), pct(o.odds), oneIn(1 / o.median), pct(o5.odds)];
});
say('## 7. Channels (illustrative)', '',
  'You meet `met` people a year through a channel, go deep with the 10 who read best, and read them with validity r.',
  'Met and r are assumptions for review; the 2017 shares are Rosenfeld, Thomas & Hausen (2019).');
say(table(['Channel', 'Couples met 2017', 'Met / yr', 'Read r', 'Pre-filter', 'P(≥ 1 in 1k) in a year', 'Best, median luck', 'P(≥ 1 in 1k) in 5 years'], chRows));

// ---------- 8. Connor's chain ----------
const cRows = [];
for (const gamma of [0.1, 0.33, 1]) for (const key of ['professional', 'uniform']) {
  const s = steadyState(JOB_TYPES[key].dist, gamma);
  cRows.push([gamma, key === 'uniform' ? 'Uniform(0, 2] (essay)' : 'lognormal CV 0.48', pct(s.PA), pct(s.PXlt1_A), s.EXA.toFixed(2), pct(s.PQ1_A)]);
}
say("## 8. Connor's chain on dating churn", '',
  'γ = time spent single / relationship length for someone exactly as advertised (the hiring page\'s dating preset is 0.33).');
say(table(['γ', 'Truth ratio', 'Single at a time', 'Single who oversell', 'Avg truth ratio of singles', 'Singles from bottom fifth'], cRows));

writeFileSync(new URL('../../docs/dating/sensitivity.md', import.meta.url), md.join('\n'));
writeFileSync(new URL('../../src/data/dating/calibration.json', import.meta.url), JSON.stringify({
  views: VIEWS,
  activity: { women: W.a, men: Mn.a },
  consensus: { womenOnMen: rhoW, menOnWomen: rhoM, ksWomenOnMen: fitW.d, ksMenOnWomen: fitM.d },
  exposure: { men: kappaW, women: kappaM },
  commitment: { kc: chosen.kc, b: chosen.b, x50: chosen.x50 },
}, null, 1));
console.log('wrote docs/dating/sensitivity.md and src/data/dating/calibration.json');
